NDefines.NAI.DIPLOMATIC_ACTION_INFLUENCE_NATION_BASE_FACTOR = 5
NDefines.NAI.DIPLOMATIC_ACTION_INFLUENCE_NATION_ALLY_FACTOR	= 25
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_DISABLE_VERSUS_PLAYER_ENEMIES = 1
NDefines.NAI.DIPLOMATIC_ACTION_OFFER_CONDOTTIERI_ONLY_MILITARY_RULERS = 0
NDefines.NAI.DIPLOMATIC_ACTION_PERSONALITY_MULT = 1.75
NDefines.NAI.DIPLOMATIC_INTEREST_DISTANCE = 175

NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_VASSALIZE_FACTOR = 200
NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_POWERBALANCE_FACTOR = 25

NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_BASE_FACTOR = 75
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_STRATEGY_FACTOR = 1.25
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_OTHER_CB_FACTOR = 1.0
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_NOT_ADJACENT_FACTOR = 0.75

NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_POWERBALANCE_FACTOR = 30
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_AI = 35
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_PLAYER = 30
NDefines.NAI.DIPLOMATIC_ACTION_GUARANTEE_POWERBALANCE_FACTOR = 35
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_ALLY_FACTOR = 75
NDefines.NAI.DIPLOMATIC_ACTION_VASSALIZE_DEVELOPMENT_FACTOR	= 10
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_EXISTING_RELATION_MULT = 25.0
NDefines.NAI.DIPLOMATIC_ACTION_MILITARY_ACCESS_ENEMY_REGIMENTS_FACTOR = 2.5
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_WAR_WITH_RIVAL_FACTOR = 25
NDefines.NAI.DIPLOMATIC_ACTION_ALLIANCE_ACCEPTANCE_MULT = 3.25
NDefines.NAI.DIPLOMATIC_ACTION_WARNING_WARN_FACTOR = 50

NDefines.NAI.DIPLOMATIC_ACTION_TAKE_ON_DEBT_ALLY_FACTOR = 50
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_INDEBTED_FACTOR = 35

NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 50.0
NDefines.NAI.MAX_SAVINGS = 175.0
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.75
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.25
NDefines.NAI.DESIRED_DEFICIT = 0.125
NDefines.NAI.DESIRED_SURPLUS = 0.125
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 3.5
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS_PEACETIME = 25.0
NDefines.NAI.DEBASE_THRESHOLD = 1000

NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.415
NDefines.NAI.ADVISOR_PROMOTION_AGE_CUTOFF = 50
NDefines.NAI.ADVISOR_MIN_SKILL_RELUCTANT_FIRE = 3
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 50.0
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 20.0

NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 0.15
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.25
NDefines.NAI.ARMY_BUDGET_FRACTION = 1.25
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.5
NDefines.NAI.FORT_BUDGET_FRACTION = 0.90

NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 2500.0
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 1500.0

NDefines.NAI.UPGRADE_CENTER_OF_TRADE_BASE_AI_DESIRE = 75.0

NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 1.0
NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.125
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 1.5
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 1.35
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 1.75
NDefines.NAIEconomy.MISSIONARY_FRACTION = 0.15
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 1.25
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 1.45
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 1.35
NDefines.NAIEconomy.NAVY_FRACTION_PEACEFUL = 1.25
NDefines.NAIEconomy.NAVY_FRACTION_CAPITALIST = 1.25
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 3.5
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 7.5
NDefines.NAIEconomy.FORT_FRACTION_MILITARIZE = 5.0
NDefines.NAIEconomy.REBEL_THREAT_MILITARIZE_THRESHOLD = 1.0

NDefines.NAI.DEVELOPMENT_CAP_BASE = 35
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1.5

NDefines.NAI.POWERBALANCE_DISABLE_VERSUS_AI = 1

NDefines.NAI.ESTATE_MAX_PRIVILEDGES = 4
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 90.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 15.0
NDefines.NAI.DANGEROUS_ESTATE_INFLUENCE_BUFFER = 7.5

NDefines.NAI.AGGRESSIVENESS = 275.0
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 625.0
NDefines.NAI.MISSION_PICK_CHANCE = 50.0
NDefines.NAI.PS_SHORT_TERM_POOL = 250.0
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 0.0
NDefines.NAI.AI_CONVERT_CULTURES = 1
NDefines.NAI.DEFENDER_OF_FAITH_BASE_AI_DESIRE = 0.25

NDefines.NAI.PEACE_DESPERATION_FACTOR = 35
NDefines.NAI.PEACE_REBELS_FACTOR = 50
NDefines.NAI.PEACE_ALLY_REBELS_MULT = 1.25
NDefines.NAI.PEACE_COALITION_FACTOR = 25
NDefines.NAI.PEACE_CAPITAL_FACTOR = 35
NDefines.NAI.PEACE_CALL_FOR_PEACE_FACTOR = 15
NDefines.NAI.PEACE_TIME_MAX_MONTHS = 120
NDefines.NAI.PEACE_TIME_MONTHS = 35
NDefines.NAI.PEACE_BASE_RELUCTANCE = 5
NDefines.NAI.PEACE_MILITARY_STRENGTH_FACTOR = 25

NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 0.35
NDefines.NAI.AI_USES_HISTORICAL_IDEA_GROUPS	= 0
NDefines.NAI.REVOLUTION_EMBRACE_MAX_ABSOLUTISM = 50
NDefines.NAI.EDICT_VALUE_THRESHOLD = 25
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 5.0
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 1.5
NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 10

NDefines.NAI.PEACE_FORCE_BALANCE_FACTOR = 0.50
NDefines.NAI.PEACE_TIME_EARLY_FACTOR = 0.5
NDefines.NAI.PEACE_TERMS_MIN_SCORE = 5
NDefines.NAI.PEACE_ALLY_BASE_RELUCTANCE_MULT = 2.5
NDefines.NAI.PEACE_WAR_DIRECTION_WINNING_MULT = 7.5
NDefines.NAI.PEACE_WAR_DIRECTION_FACTOR = 0.75
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_FACTOR = 2.25
NDefines.NAI.PEACE_HIGH_WAR_EXHAUSTION_THRESHOLD = 10
NDefines.NAI.PEACE_WAR_EXHAUSTION_FACTOR = 1.25
NDefines.NAI.PEACE_TERMS_STRATEGY_MULT = 0.75
NDefines.NAI.PEACE_TERMS_BASE_SCORE = 25
NDefines.NAI.PEACE_EXCESSIVE_DEMANDS_THRESHOLD = 15
NDefines.NAI.PEACE_EXCESSIVE_DEMANDS_FACTOR = 0.005
NDefines.NAI.PEACE_TERMS_PROVINCE_IMPERIAL_LIBERATION_MULT = 5.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_CB_MULT = 1.0
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 5.0
NDefines.NAI.PEACE_TERMS_PROVINCE_WARGOAL_MULT = 2.5
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 3.5
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_CULTURE_MULT = 0.90
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_INTEREST_MULT = 0.35
NDefines.NAI.PEACE_TERMS_RELEASE_VASSALS_BASE_MULT = 0.90
NDefines.NAI.PEACE_TERMS_TRANSFER_VASSALS_BASE_MULT = 0.75
NDefines.NAI.PEACE_TERMS_PROVINCE_REAL_ADJACENT_MULT = 1.15
NDefines.NAI.PEACE_TERMS_PROVINCE_VASSAL_MULT = 0.90
NDefines.NAI.PEACE_TERMS_RETURN_CORES_VASSAL_MULT = 25.0
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_ADJACENT_MULT = 0.35

NDefines.NAI.TRANSPORT_FRACTION = 0.25

NDefines.NAI.ONLY_INFANTRY_MERCS = 0

NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 125

NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 150
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT	= 0.75
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 7.5
NDefines.NAI.PURSUE_DISTANCE = 100

NDefines.NAI.INVADING_MAX_AWAY_RATIO = 1.75
NDefines.NAI.INVADING_BRAVERY = 1.5
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 15

NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 7.5
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.25
NDefines.NAI.MAX_TASKS_NEW_REGION_ASSIGN_ALGORITHM = 300
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 100

NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 50
NDefines.NAI.ARTILLERY_FRACTION = 0.40
NDefines.NAI.MIN_CAV_PERCENTAGE = 10
NDefines.NAI.MAX_CAV_PERCENTAGE = 40
NDefines.NAI.REGIMENTS_PER_GENERAL = 50

NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.50

NDefines.NAI.IMPORTANT_PROVINCE_THRESHOLD = 0.035

NDefines.NAI.PEACE_DESIRE_AI_PREFS_QUICK_PEACE = 50

NDefines.NAI.MIN_SCORE_TO_CONCENTRATE_DEVELOPMENT = 1.5